//! Log entries (atomic operations)

/// An atomic, batched operation in the sigchain.
///
/// Entries are the fundamental unit of change in Lattice.
/// The KV store is a "view" generated by replaying these entries.
pub struct Entry {
    // TODO: operation data, signature, prev_hash
}
