//! Lattice Store
//!
//! Log-based Key-Value store:
//! - State is a "view" generated by replaying entries
//! - Watermarks for agreeing on safe compaction points
//! - Snapshots for replacing old logs

pub mod store;
pub mod snapshot;
pub mod watermark;

pub use store::Store;
