baseURL = "https://latticesync.org/"
languageCode = "en-us"
title = "Lattice"
theme = "lattice-theme"

[markup]
  [markup.highlight]
    noClasses = false
    codeFences = true
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 3
